export type DataTtd = {
  header1 : string,
  header2 : string,
  header3 : string,
  header4  : string,
  nama1 : string,
  jab1 : string,
  nik1 : string,
  nama2 : string,
  jab2 : string,
  nik2 : string,
  nama3 : string,
  jab3 : string,
  nik3 : string,
  nama4 : string,
  jab4 : string,
  nik4 : string,
  nama5 : string,
  jab5 : string,
  nik5 : string,
}